# 网站信息
title: Yanz's Blog
subtitle: ''
description: ''
keywords: null
author: Yanz
language: zh-CN
timezone: ''

# 部署配置
root: /
url: http://121.37.132.165
relative_link: true   # 启用相对链接

# 文章链接
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true

# 目录设置
source_dir: source
public_dir: public
tag_dir: Tags
archive_dir: Articles
category_dir: Categories
code_dir: downloads/code
i18n_dir: ':lang'

# 渲染与文件名设置
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false

# 外部链接设置
external_link:
  enable: true
  field: site
  exclude: ''

# 文件名与文章设置
filename_case: 0
render_drafts: false
post_asset_folder: false
future: true

# 语法高亮
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# 分页与索引
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
per_page: 10
pagination_dir: page

# 分类与标签
default_category: uncategorized
category_map: null
tag_map: null

# 其他
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
include: null
exclude: null
ignore: null

# 主题
theme: nexmoe

# 部署
deploy:
  type: ''

# 本地服务
server:
  port: 4001

# Feed 设置
feed:
  type: atom
  path: atom.xml
  limit: 20
