# ç½‘ç«™åŸºç¡€è®¾ç½®
avatar: /images/logo.jpg        # ç½‘ç«™ Logo
background:                     # åšå®¢èƒŒæ™¯åŠæ–‡ç« é»˜è®¤å¤´å›¾
  path: https://imageurl.kuri.ink/images/logo.png
  width: 1280
  height: 726
favicon:
  href: /favicon.ico            # ç½‘ç«™å›¾æ ‡
  type: image/x-icon            # å›¾æ ‡ç±»å‹ (image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

# åŠŸèƒ½å¼€å…³
function:
  globalToc: true               # è‡ªåŠ¨ç”Ÿæˆæ–‡ç«  TOC
  wordCount: false              # æ–‡ç« å­—æ•°ç»Ÿè®¡
  copyCode: true                # å…è®¸å¤åˆ¶ä»£ç å—

# å›¾ç‰‡ CDN é…ç½®
imageCDN:
  enable: false                 # æ˜¯å¦å¼€å¯å›¾ç‰‡ CDN
  origin: /../../images/        # å›¾ç‰‡åŸå§‹ç›®å½•
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # CDN åŸŸå

# è‡ªå®šä¹‰æ ·å¼
customStyles:
  - custom.css                  # å¯åœ¨ source æ–‡ä»¶å¤¹ä¸‹æ–°å»º custom.css

# é™„åŠ å›¾æ ‡åº“
iconlib: //at.alicdn.com/t/c/font_5072468_u5zojahqgl.css

# èœå•é…ç½®
menu:
  å›åˆ°é¦–é¡µ:
    - /
    - iconfont icon-shouye
  Me & Blog:
    - /aboutme
    - iconfont icon-me
  å‹æƒ…é“¾æ¥:
    - /links
    - iconfont icon-youqinglianjie
  è¯·æ¯å’–å•¡:
    - /tip
    - iconfont icon-1

# å°å·¥å…·ï¼ˆWidgetsï¼‰
widgets:
  - name: search
    display_name: æœç´¢
    enable: true
    options:
      placeholder: æœç´¢
      search:
        type: engine            # å¯é€‰ engineã€swiftypeã€local
        url: https://cn.bing.com/search?q=
        id: <swiftype-id>
  - name: social
    enable: true
    options:
      social:
        å“”å“©å“”å“©:
          - https://space.bilibili.com/690934177
          - icon-bilibili
          - rgb(231, 106, 141)
          - rgba(231, 106, 141, .1)
        GitHub:
          - https://github.com/Big-521/
          - icon-github
          - rgb(25, 23, 23)
          - rgba(25, 23, 23, .1)
        çŸ¥ä¹:
          - https://www.zhihu.com/people/yanz-33-38
          - icon-zhihu
          - rgb(30, 136, 229)
          - rgba(30, 136, 229, .1)
        RSS:
          - http://121.37.132.165:4001/atom.xml
          - icon-rss
          - rgb(247, 132, 34)
          - rgba(247, 132, 34, .1)
  - name: category
    enable: true
  - name: tagcloud
    enable: true
    options:
      maxTagcloud: 17           # æ ‡ç­¾äº‘æ˜¾ç¤ºæ•°é‡ï¼Œ0 è¡¨ç¤ºä¸é™åˆ¶
  - name: hitokoto
    enable: false
    options:
      widgetHitokoto:
        loading_placeholder: "ğŸš€ è·å–ä¸­..."
        loading_error_placeholder: "ğŸ è·å–å¤±è´¥..."
        category: []
  - name: archive
    enable: false
    options:
      widgetAchive:
        archive_type: "year"     # æŒ‰å¹´æˆ–æŒ‰æœˆå±•ç¤º
        show_count: true
  - name: recent_posts
    enable: false
  - name: link
    enable: false
    options:
      widgetLink:
        - title: æŠ˜å½±è½»æ¢¦
          img: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/avatar.png
          link: https://nexmoe.com/

# å¤åˆ¶æç¤ºæ–‡æ¡ˆ
copyTip: "âš ï¸ æœ¬æ–‡å†…å®¹ç¦æ­¢æœªç»è®¸å¯è½¬è½½ã€‚\nå¼•ç”¨è¯·æ³¨æ˜å‡ºå¤„ï¼š%url"

# é¡µå¤´æ’æ§½
slotHead: |
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-4D4ZJ9G024"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag("js", new Date());
    gtag("config", "G-4D4ZJ9G024");
  </script>

# é¡µè„šæ’æ§½ï¼ˆå¯é€‰ï¼‰
# slotFooter: |
#   <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2058306854838448" crossorigin="anonymous"></script>

# ä¾§è¾¹æ æ’æ§½ï¼ˆå¯é€‰ï¼‰
# slotSidebar: |
#   <br><a target="_blank" href="https://beian.miit.gov.cn/">é„‚ICPå¤‡2020018486å·</a>
#   <br><a target="_blank" href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral">
#   <img src="https://i.dawnlab.me/c0268c1e6cfd0863d6ba35be1575941a.png" width="150px"></a>

# è¯„è®ºæ’æ§½ï¼ˆå¯é€‰ï¼‰
# slotComment: |
#   <link rel="stylesheet" href="https://cdn.staticfile.org/gitalk/1.8.0/gitalk.css">
#   <script src="https://cdn.staticfile.org/gitalk/1.8.0/gitalk.min.js"></script>
#   <div id="gitalk-container"></div>
#   <script>
#     var fixedCallback = 'http://localhost:4001/callback';
#     Gitalk.prototype._getUrl = function () {
#       var url = 'https://github.com/login/oauth/authorize';
#       url += '?client_id=' + this.clientID;
#       url += '&redirect_uri=' + encodeURIComponent(fixedCallback);
#       url += '&scope=' + this.scope;
#       return url;
#     };
#     var gitalk = new Gitalk({
#       clientID: 'Ov23li1m0FY9ISyXi4Fv',
#       clientSecret: '6cfd7137425314dfb0a6432f187a8f49a48450c9',
#       repo: 'Comment-Repository',
#       owner: 'Big-521',
#       admin: ['Big-521'],
#       id: location.pathname,
#       distractionFreeMode: false,
#       language: 'zh-CN'
#     });
#     gitalk.render('gitalk-container');
#   </script>

# ç‰ˆæƒå£°æ˜æ’æ§½
slotCopyright: |
  <strong>ç‰ˆæƒå£°æ˜ï¼š</strong>æœ¬æ–‡é‡‡ç”¨ <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> åè®®è¿›è¡Œè®¸å¯
